language: python
python:
    - "3.6"
    - "3.8"

dist: xenial

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest pytest-cov pytest-xdist coverage
  - python setup.py install
script:
  - PYTHONPATH=$PWD:$PYTHONPATH py.test --cov timesynth

after_success:
  - codecov
